"""
Parse blanks_output.txt and extract accepted city assignments for city_fixes.json.

Canonical names, valid-name whitelist, distance thresholds, and skip rules
all live in config/city_canonical.yaml. To accept a new raw name, add a
canonical mapping there — do not edit this file.

A Unicode-fold fallback lookup catches diacritic/transliteration variants
(e.g. "Polack" → "Polatsk" if Polatsk-variants are mapped) so common
spellings don't need to be enumerated one-by-one.
"""
import re, json, sys, io, unicodedata
from pathlib import Path
import yaml

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

INPUT = 'C:/tmp/blanks_output.txt'
CANONICAL_YAML = 'config/city_canonical.yaml'

with open('config/city_fixes.json', encoding='utf-8') as f:
    existing = set(k for k in json.load(f).keys() if not k.startswith('_'))

with open(CANONICAL_YAML, encoding='utf-8') as f:
    cfg = yaml.safe_load(f)

CANONICAL_MAP    = cfg.get('canonical_map', {})
VALID_CANONICAL  = set(cfg.get('valid_canonical', []))
LARGE_CANONICAL  = set(cfg.get('large_canonical', []))
THRESHOLDS       = cfg.get('thresholds', {}) or {}
DEFAULTS         = cfg.get('default_thresholds', {}) or {}
LARGE_KM         = float(DEFAULTS.get('large_km', 8.0))
SMALL_KM         = float(DEFAULTS.get('small_km', 5.5))
SKIP_SET         = set(cfg.get('skip_set', []))
SKIP_PATTERNS    = [re.compile(p) for p in cfg.get('skip_patterns', [])]


def fold(s: str) -> str:
    """Lowercase + NFKD + strip combining marks. Cyrillic stays cyrillic."""
    return ''.join(
        c for c in unicodedata.normalize('NFKD', s.casefold())
        if not unicodedata.combining(c)
    )


# Pre-compute folded lookup for canonical_map + valid_canonical (canonical→canonical).
_FOLDED_LOOKUP = {fold(k): v for k, v in CANONICAL_MAP.items()}
for c in VALID_CANONICAL:
    _FOLDED_LOOKUP.setdefault(fold(c), c)


def canonicalize(raw: str) -> str | None:
    """Direct map → folded fallback. Returns None if not recognized."""
    if raw in CANONICAL_MAP:
        return CANONICAL_MAP[raw]
    if raw in VALID_CANONICAL:
        return raw
    return _FOLDED_LOOKUP.get(fold(raw))


def threshold_for(canonical: str) -> float:
    if canonical in THRESHOLDS:
        return float(THRESHOLDS[canonical])
    return LARGE_KM if canonical in LARGE_CANONICAL else SMALL_KM


line_re = re.compile(r'ts=(\S+)\s+lat=([\d.-]+)\s+lng=([\d.-]+)\s+->\s+(.+?)\s+\(([\d.]+)km\)')

results: dict[str, list[str]] = {}

with open(INPUT, encoding='utf-8') as f:
    for line in f:
        m = line_re.search(line)
        if not m:
            continue
        ts, _lat_s, _lng_s, raw_city, dist_s = m.groups()
        dist = float(dist_s)

        if ts in existing:
            continue
        if raw_city in SKIP_SET:
            continue
        if any(p.search(raw_city) for p in SKIP_PATTERNS):
            continue

        canonical = canonicalize(raw_city)
        if not canonical or canonical not in VALID_CANONICAL:
            continue

        if dist > threshold_for(canonical):
            continue

        results.setdefault(canonical, []).append(ts)

total = sum(len(v) for v in results.values())
print(f"// Total cities: {len(results)}, total entries: {total}")
for city in sorted(results.keys()):
    ids = results[city]
    print(f"\n  // === {city} ({len(ids)} entries) ===")
    for ts in ids:
        print(f'  "{ts}": "{city}",')
